[package]
name = "rms_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
postgres = {version = "0.19.12", features =["with-uuid-1"] }
sha2 = "0.10.9"
uuid = {version = "1.19.0", features = ["v4"]}
